manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      - name: penguinchat
      url-base: https://github.com/penguinchat
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-for-a-keyboard
      remote: penguinchat
      revision: main
  self:
    path: config
